
#LOCAL//DEV ??
spring:
  config:
    activate:
      on-profile: local,dev
  datasource:
    # ?? ??? ????.
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/apartment
    username: root
    password: 1q2w3e4r!@#
  jpa:
    hibernate:
      ddl-auto: create-drop


---

spring:
  config:
    activate:
      on-profile: master
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true
      path: /h2-console
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/security
    username: sa
    password: 1234